"""Checkpoint B4: stage 8 kinematics core, proven against synthetic pose
arrays with known ground truth -- the constant-velocity descent test is
one of the three places (per overnight-prompt.md) tests earn their keep."""

from __future__ import annotations

import cv2
import numpy as np
import pytest

from pipeline.config import KinematicsConfig
from pipeline.contracts import CalibrationRecord
from pipeline.stages.kinematics import (
    PoleFrame,
    apply_likelihood_filter,
    compute_pole_frame,
    compute_trial_kinematics,
    compute_velocity,
    detect_descent_threshold_crossing,
    height_fraction,
    interpolate_gaps,
    occlusion_fraction,
    pole_landmark_drift_flagged,
    scale_to_mm,
    smooth,
    to_kinematics_long_rows,
    to_trial_summary_row,
    undistort_points,
    velocity_by_height,
)

IDENTITY_CALIBRATION = CalibrationRecord(
    camera_serial="mock", epoch_id="epoch-1",
    camera_matrix=((1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, 1.0)),
    distortion_coefficients=(0.0, 0.0, 0.0, 0.0, 0.0),
)

DEFAULT_CONFIG = KinematicsConfig(
    likelihood_cutoff=0.5, max_gap_frames=5, smoothing_method="median", smoothing_window=3,
    descent_rule_name="threshold_crossing_v1", descent_rule_onset_height_fraction=0.95,
    descent_rule_offset_height_fraction=0.05, pole_landmark_drift_threshold_mm=5.0,
)


# -- step 1: likelihood filter --

def test_apply_likelihood_filter_masks_below_cutoff():
    x = np.array([1.0, 2.0, 3.0])
    y = np.array([10.0, 20.0, 30.0])
    likelihood = np.array([0.9, 0.3, 0.9])
    x_f, y_f = apply_likelihood_filter(x, y, likelihood, cutoff=0.5)
    assert np.isnan(x_f[1]) and np.isnan(y_f[1])
    assert x_f[0] == 1.0 and x_f[2] == 3.0


# -- step 2: gap interpolation --

def test_interpolate_gaps_short_gap_is_filled():
    arr = np.array([1.0, np.nan, np.nan, 4.0])  # gap of 2
    result = interpolate_gaps(arr, max_gap_frames=2)
    np.testing.assert_allclose(result, [1.0, 2.0, 3.0, 4.0])


def test_interpolate_gaps_long_gap_stays_nan():
    """A gap longer than max_gap_frames must stay NaN -- never silently
    bridged (overnight-prompt.md explicit requirement)."""
    arr = np.array([1.0, np.nan, np.nan, np.nan, np.nan, 6.0])  # gap of 4
    result = interpolate_gaps(arr, max_gap_frames=2)
    assert np.all(np.isnan(result[1:5]))
    assert result[0] == 1.0 and result[5] == 6.0


def test_interpolate_gaps_edge_gap_stays_nan():
    arr = np.array([np.nan, np.nan, 3.0, 4.0])  # leading edge gap
    result = interpolate_gaps(arr, max_gap_frames=5)
    assert np.all(np.isnan(result[:2]))


# -- step 3: smoothing --

def test_smooth_median_preserves_unfilled_nan_positions():
    arr = np.array([1.0, 2.0, np.nan, np.nan, np.nan, np.nan, 7.0])  # gap of 4, too long for max_gap=2
    interpolated = interpolate_gaps(arr, max_gap_frames=2)
    smoothed = smooth(interpolated, "median", window=3)
    assert np.all(np.isnan(smoothed[2:6]))


def test_smooth_unknown_method_raises():
    with pytest.raises(ValueError):
        smooth(np.array([1.0, 2.0, 3.0]), "not_a_real_method", window=3)


def test_smooth_median_is_near_identity_on_a_linear_ramp():
    arr = np.linspace(0.0, 100.0, 50)
    smoothed = smooth(arr, "median", window=3)
    np.testing.assert_allclose(smoothed[1:-1], arr[1:-1], atol=1e-9)


# -- step 4: undistortion --

def test_undistort_points_identity_calibration_is_passthrough():
    x = np.array([10.0, 20.0, np.nan])
    y = np.array([30.0, 40.0, np.nan])
    x_u, y_u = undistort_points(x, y, IDENTITY_CALIBRATION)
    np.testing.assert_allclose(x_u[:2], x[:2], atol=1e-6)
    np.testing.assert_allclose(y_u[:2], y[:2], atol=1e-6)
    assert np.isnan(x_u[2]) and np.isnan(y_u[2])


def test_undistort_points_recovers_true_pixels_with_real_distortion():
    """Ground truth generated by cv2.projectPoints itself: distort known
    object points into pixel space, then confirm undistort_points recovers
    the same pixels a zero-distortion projection would have produced."""
    camera_matrix = np.array([[800.0, 0.0, 320.0], [0.0, 800.0, 240.0], [0.0, 0.0, 1.0]])
    dist_coeffs = np.array([0.1, -0.05, 0.001, 0.001, 0.0])
    calibration = CalibrationRecord(
        camera_serial="s", epoch_id="e",
        camera_matrix=tuple(tuple(row) for row in camera_matrix),
        distortion_coefficients=tuple(dist_coeffs),
    )

    object_points = np.array([[0.05, 0.03, 1.0], [-0.02, 0.04, 1.0], [0.0, 0.0, 1.0]])
    rvec = np.zeros(3)
    tvec = np.zeros(3)
    distorted, _ = cv2.projectPoints(object_points, rvec, tvec, camera_matrix, dist_coeffs)
    distorted = distorted.reshape(-1, 2)
    true_pixels, _ = cv2.projectPoints(object_points, rvec, tvec, camera_matrix, np.zeros(5))
    true_pixels = true_pixels.reshape(-1, 2)

    x_u, y_u = undistort_points(distorted[:, 0], distorted[:, 1], calibration)

    np.testing.assert_allclose(x_u, true_pixels[:, 0], atol=0.5)
    np.testing.assert_allclose(y_u, true_pixels[:, 1], atol=0.5)


# -- pole-landmark coordinate frame --

def test_compute_pole_frame_uses_median_of_static_landmarks():
    top_x = np.array([100.0, 101.0, 99.0])
    top_y = np.array([100.0, 100.0, 100.0])
    base_x = np.array([100.0, 100.0, 100.0])
    base_y = np.array([500.0, 500.0, 501.0])
    frame = compute_pole_frame(top_x, top_y, base_x, base_y)
    assert frame.top_xy == (100.0, 100.0)
    assert frame.base_xy == (100.0, 500.0)
    assert frame.pixel_length == pytest.approx(400.0)


def test_height_fraction_at_endpoints():
    frame = PoleFrame(base_xy=(100.0, 500.0), top_xy=(100.0, 100.0), pixel_length=400.0)
    frac = height_fraction(np.array([100.0, 100.0]), np.array([100.0, 500.0]), frame)
    assert frac[0] == pytest.approx(1.0)
    assert frac[1] == pytest.approx(0.0)


def test_scale_to_mm():
    result = scale_to_mm(np.array([1.0, 0.5, 0.0]), pole_length_mm=1000.0)
    np.testing.assert_allclose(result, [1000.0, 500.0, 0.0])


def test_pole_landmark_drift_flagged_true_when_landmark_moves():
    top_x = np.array([100.0] * 9 + [150.0])  # one frame jumps 50px
    top_y = np.array([100.0] * 10)
    base_x = np.array([100.0] * 10)
    base_y = np.array([500.0] * 10)
    assert pole_landmark_drift_flagged(top_x, top_y, base_x, base_y, pole_length_mm=1000.0, threshold_mm=5.0) is True


def test_pole_landmark_drift_not_flagged_when_stable():
    top_x = np.full(10, 100.0)
    top_y = np.full(10, 100.0)
    base_x = np.full(10, 100.0)
    base_y = np.full(10, 500.0)
    assert pole_landmark_drift_flagged(top_x, top_y, base_x, base_y, pole_length_mm=1000.0, threshold_mm=5.0) is False


# -- velocity --

def test_compute_velocity_of_a_linear_ramp_is_constant():
    fps = 30.0
    height_mm = np.linspace(1000.0, 0.0, 61)  # -1000mm over 60 frames = -500mm/s at 30fps
    velocity = compute_velocity(height_mm, fps)
    np.testing.assert_allclose(velocity[2:-2], -500.0, atol=1e-6)


def test_velocity_by_height_bins_group_correctly():
    height_frac = np.array([0.05, 0.15, 0.55, 0.95])
    velocity = np.array([-10.0, -20.0, -30.0, -40.0])
    df = velocity_by_height(height_frac, velocity, n_bins=10)
    assert len(df) == 10
    assert df.iloc[0]["mean_velocity_mm_s"] == pytest.approx(-10.0)
    assert df.iloc[0]["n_samples"] == 1


# -- descent rule --

def test_detect_descent_threshold_crossing_basic():
    height_frac = np.array([1.0, 0.99, 0.5, 0.5, 0.04, 0.0])
    onset, offset = detect_descent_threshold_crossing(height_frac, onset_fraction=0.95, offset_fraction=0.05)
    assert onset == 2  # first frame <= 0.95
    assert offset == 4  # first frame at/after onset that's <= 0.05


def test_detect_descent_threshold_crossing_no_descent_returns_none():
    height_frac = np.array([1.0, 0.99, 0.97])  # never crosses onset threshold
    onset, offset = detect_descent_threshold_crossing(height_frac, onset_fraction=0.95, offset_fraction=0.05)
    assert onset is None and offset is None


def test_occlusion_fraction():
    likelihood = np.array([0.9, 0.1, 0.9, 0.1])
    assert occlusion_fraction(likelihood, cutoff=0.5) == pytest.approx(0.5)


# -- the ground-truth end-to-end test --

def _build_synthetic_constant_velocity_descent():
    """Rat sits at the pole top, descends at a perfectly constant velocity,
    then sits at the base -- the ground-truth scenario B4 explicitly asks
    for: 'a fabricated constant-velocity descent must recover the correct
    velocity.'
    """
    fps = 30.0
    pole_length_mm = 1000.0
    base_xy = (100.0, 500.0)
    top_xy = (100.0, 100.0)

    idle_before_frac = np.full(10, 1.0)
    ramp_frac = np.linspace(1.0, 0.0, 61)  # exactly -500mm/s at 30fps (see velocity test above)
    idle_after_frac = np.full(10, 0.0)
    frac = np.concatenate([idle_before_frac, ramp_frac, idle_after_frac])

    y = base_xy[1] - (base_xy[1] - top_xy[1]) * frac  # invert height_fraction's affine map
    x = np.full_like(y, 100.0)  # directly on the pole axis: zero perpendicular offset
    likelihood = np.full_like(y, 1.0)

    n = len(y)
    pole_top_x = np.full(n, top_xy[0])
    pole_top_y = np.full(n, top_xy[1])
    pole_base_x = np.full(n, base_xy[0])
    pole_base_y = np.full(n, base_xy[1])

    return x, y, likelihood, pole_top_x, pole_top_y, pole_base_x, pole_base_y, fps, pole_length_mm


def test_constant_velocity_descent_recovers_correct_velocity():
    x, y, likelihood, pt_x, pt_y, pb_x, pb_y, fps, pole_length_mm = _build_synthetic_constant_velocity_descent()

    result = compute_trial_kinematics(
        x, y, likelihood, pt_x, pt_y, pb_x, pb_y,
        calibration=IDENTITY_CALIBRATION, config=DEFAULT_CONFIG,
        pole_length_mm=pole_length_mm, fps=fps,
    )

    assert result.descent_onset_frame is not None
    assert result.descent_offset_frame is not None
    assert result.mean_velocity_mm_s == pytest.approx(500.0, rel=0.05)
    # onset/offset trim inward from the full ramp at the 0.95/0.05 crossings
    # (frac[3]=0.95, frac[57]=0.05 within the 61-point ramp): (57-3)/30 = 1.8s,
    # not the full ramp's ~1.97s.
    assert result.descent_duration_s == pytest.approx(1.8, rel=0.05)
    assert result.pole_landmark_drift_flagged is False
    assert result.occlusion_fraction == pytest.approx(0.0)
    assert result.height_mm[0] == pytest.approx(1000.0, abs=1.0)
    assert result.height_mm[-1] == pytest.approx(0.0, abs=1.0)
    np.testing.assert_allclose(result.perpendicular_mm, 0.0, atol=1e-6)


def test_constant_velocity_descent_with_a_short_occlusion_gap_still_recovers_velocity():
    """The same scenario, but with a short mid-descent occlusion (likelihood
    drop) that's well within max_gap_frames -- gap interpolation should
    bridge it cleanly enough that velocity recovery is unaffected."""
    x, y, likelihood, pt_x, pt_y, pb_x, pb_y, fps, pole_length_mm = _build_synthetic_constant_velocity_descent()
    likelihood = likelihood.copy()
    likelihood[40:43] = 0.1  # 3-frame occlusion, within max_gap_frames=5

    result = compute_trial_kinematics(
        x, y, likelihood, pt_x, pt_y, pb_x, pb_y,
        calibration=IDENTITY_CALIBRATION, config=DEFAULT_CONFIG,
        pole_length_mm=pole_length_mm, fps=fps,
    )

    assert result.mean_velocity_mm_s == pytest.approx(500.0, rel=0.05)
    assert result.is_interpolated[40:43].all()


def test_constant_velocity_descent_with_a_long_occlusion_gap_stays_nan_in_output():
    """A gap longer than max_gap_frames must stay NaN all the way through
    to the final height_mm output -- never silently bridged."""
    x, y, likelihood, pt_x, pt_y, pb_x, pb_y, fps, pole_length_mm = _build_synthetic_constant_velocity_descent()
    likelihood = likelihood.copy()
    likelihood[40:50] = 0.1  # 10-frame occlusion, beyond max_gap_frames=5

    result = compute_trial_kinematics(
        x, y, likelihood, pt_x, pt_y, pb_x, pb_y,
        calibration=IDENTITY_CALIBRATION, config=DEFAULT_CONFIG,
        pole_length_mm=pole_length_mm, fps=fps,
    )

    assert np.all(np.isnan(result.height_mm[40:50]))
    assert not result.is_interpolated[40:50].any()


def test_trial_summary_and_kinematics_long_rows_are_consistent():
    x, y, likelihood, pt_x, pt_y, pb_x, pb_y, fps, pole_length_mm = _build_synthetic_constant_velocity_descent()
    result = compute_trial_kinematics(
        x, y, likelihood, pt_x, pt_y, pb_x, pb_y,
        calibration=IDENTITY_CALIBRATION, config=DEFAULT_CONFIG,
        pole_length_mm=pole_length_mm, fps=fps,
    )

    summary = to_trial_summary_row("uid-1", "mid_back", result)
    long_rows = to_kinematics_long_rows("uid-1", "lateral_L", "mid_back", result)

    assert summary.trial_uid == "uid-1"
    assert summary.mean_velocity_mm_s == pytest.approx(result.mean_velocity_mm_s)
    assert len(long_rows) == len(result.height_mm)
    assert long_rows[0].trial_uid == "uid-1"
    assert long_rows[0].view == "lateral_L"
